### ISSUE TITLE
Portuguese version of DLang Tour

### ISSUE THREAD

**Issue by sergiors** [dlang-tour/english#120]
Hi, I'm translating the repository to Portuguese version.

What should I do to transfer the repository to dlang-tour?

WIP - https://github.com/sergiors/portuguese

**Comment by wilzbach** [comment]
Wow that's great news :)

You can either transfer it via settings in the Github settings or let us clone it and create it. Whatever is more comfortable for you.

**Comment by sergiors** [comment]
@wilzbach I can't transfer because I'm not admin in dlang-tour.
Could you clone the repository? :D

**Comment by wilzbach** [comment]
> @wilzbach I can't transfer because I'm not admin in dlang-tour.

Oh sorry.

>Could you clone the repository? :D

Yep done :)
Also sent out an invitation to you for Portuguese team.

**Comment by wilzbach** [comment]
A couple of pointers:

- Request to be added as submodule @ the base repo: https://github.com/stonemaster/dlang-tour/issues/493
- https://github.com/dlang-tour/portuguese

Please note:
- I had to rewrite the last git commit to trigger the first Travis CI build (so please do a fresh clone)
- We have force-push protection & Travis CI enabled for all repos - this allows us to check that all code actually compiles etc. - hence you can't push directly, but can make use of the nice PR flow
- Once the submodule is enabled at the main tour, new commits to the master branch of the translation submodule will be automatically deployed to tour.dlang.org :)

Please let us know if you have more questions or run into any troubles!

**Comment by wilzbach** [comment]
> Once the submodule is enabled at the main tour

-> https://tour.dlang.org/tour/pt

Feel free to make a PR to http://tour.dlang.org/tour/en/welcome/languages (https://github.com/dlang-tour/english/edit/master/welcome/languages.md) yourself ;-)

**Comment by sergiors** [comment]
👯 thanks @wilzbach!

I will do my best!
