### ISSUE TITLE
Is text description for Casear encryption wrong?

### ISSUE THREAD

**Issue by mywtfmp3** [dlang-tour/english#232]
https://tour.dlang.org/tour/en/basics/arrays

> Complete the function `encrypt` to decrypt the secret message. The text should be encrypted using *Caesar encryption*, which shifts the characters in the alphabet using a certain index. The to-be-encrypted text only contains characters in the range a-z, which should make things easier. 

I am trying to translate this text. However, I am confused with the description.

I think here we want to encrypt the clear text, not to **decrypt the secret message**. Am I wrong, or I lack programmer's humor?

**Comment by ZombineDev** [comment]
You're right - it should be "encrypt" - thanks for noticing!
https://github.com/dlang-tour/english/pull/234/files

**Comment by ZombineDev** [comment]
Fixed in #234.
