### ISSUE TITLE
on basics/type-qualifiers - example's writeln output consistency - proposal

### ISSUE THREAD

**Issue by astoliar** [dlang-tour/english#250]
(this issues was presented at https://github.com/dlang-tour/spanish/pull/23)

I think this is a small issue of consistency in the example that might confuse someone.

The example is about mutability qualifiers but also shows how to use the typeof( .. ).tostring() to obtain a human-readable string of that type. At line 18 it says:

```
const int* cm = &m;
writeln("cm: ", typeof(cm).stringof);
```

and few lines down (line 37) it says:

```
const int* cv = &v;
writeln("*cv: ", typeof(cv).stringof);
```

there is no consistency between the two sections of the example. If the first writln text is correct then the text of the second writeln should say "cv" and not "\*cv". You know, the output of typeof(\*cv).stringof is not the same that typeof(cv).stringof, like "\*cv: const(int*)" is not the same that "cv: const(int*)".

I think that the * must be removed from the second writeln.

**Comment by wilzbach** [comment]
Yes I agree that this is an oversight. I quickly submitted the PR for you: https://github.com/dlang-tour/english/pull/251

**Comment by astoliar** [comment]
Great. Thanks
