### ISSUE TITLE
on basics/ranges - possible wrong instance

### ISSUE THREAD

**Issue by astoliar** [dlang-tour/english#253]
Please, take a look at the last comment "Usually this is summarized as" on https://github.com/dlang-tour/english/blob/master/basics/ranges.md. The struct instance used in the next sentence, 'fib10', is not the starting point to "summarize" the previous sentences. It should be 'fib'. 
Also, of course, it is not very useful to do 'fib10.take(10)', then I think it is a typo and the author wanted to write 'fib.take(10)'.

What do you think?

**Comment by wilzbach** [comment]
> Also, of course, it is not very useful to do 'fib10.take(10)', then I think it is a typo and the author wanted to write 'fib.take(10)'.

I agree. It should be `fib.take(10)`
