### ISSUE TITLE
byexample/code-generation-parser example doesn't compile

### ISSUE THREAD

**Issue by SMietzner** [dlang-tour/english#261]
`rdmd playground.d

onlineapp.d(14): Error: template onlineapp.main.each!((e) => conf.parse(e)).each cannot deduce function from argument types !()(Result), candidates are:
/dlang/dmd/linux/bin64/../../src/phobos/std/algorithm/iteration.d(904):        onlineapp.main.each!((e) => conf.parse(e)).each(Range)(Range r) if (!isForeachIterable!Range && (isRangeIterable!Range || __traits(compiles, typeof(r.front).length)))
/dlang/dmd/linux/bin64/../../src/phobos/std/algorithm/iteration.d(943):        onlineapp.main.each!((e) => conf.parse(e)).each(Iterable)(auto ref Iterable r) if (isForeachIterable!Iterable || __traits(compiles, Parameters!(Parameters!(r.opApply))))
`

https://tour.dlang.org/tour/en/byexample/code-generation-parser
https://github.com/dlang-tour/english/blob/master/byexample/code-generation-parser.md

**Comment by wilzbach** [comment]
Thanks a lot for the ping.
I added a quick fix from my phone: https://github.com/dlang-tour/english/pull/262

I don't know how this passed and got through our CI systems, but I will investigate once I am back home in a few days.

**Comment by SMietzner** [comment]
Someone added extra curly brackets in the switch statement, and it does compiles now. 
The reason for this should be explained in description, because it is not obvious why these are mandatory.

**Comment by SMietzner** [comment]
I would propose this as example code:
```
import std.algorithm, std.conv, std.range,
        std.stdio, std.traits;
struct Config
{
    int runs, port;
    string name;
}
void main()
{
    Config conf;
    // use the generated parser for each entry
    "runs=1,port=2,name=hello"
        .splitter(",")
        .each!(e => conf.parse(e));
    conf.writeln;
}
void parse(Conf)(ref Conf c, string entry)
{
    auto r = entry.splitter("=");
    auto key = r.front, value = r.dropOne.front;
    Switch: switch (key)
    {
        static foreach (idx, field; Conf.tupleof)
        { 
            case field.stringof:
                c.tupleof[idx] =value.to!(typeof(field));
                break Switch;
        }
        default:
        assert (0, "Unknown member name.");
    }
}
```

**Comment by wilzbach** [comment]
Good idea. I just wanted to fix it.
Would you mind opening a PR for your proposed improvement?
(it's really hard to do this from my phone and I am still backpacking for a few days)

**Comment by Basile-z** [comment]
works for me
