### ISSUE TITLE
Doc examples doesn't run due to dependency error

### ISSUE THREAD

**Issue by drug007** [dlang-tour/english#270]
If you try to run example from documentation you get:

Compilation output: 
Unresolvable dependencies to package mir-algorithm:
  onlineapp ~master depends on mir-algorithm ~>2.0.2

**Comment by ZombineDev** [comment]
I'm working on fixing the docker build.

**Comment by ZombineDev** [comment]
There were issues on all three layers:
* core-exec
* core
* The dub examples on each language repo

@wilzbach fixed the tests in core-exec and I fixed the rest and we should all good now.
