### ISSUE TITLE
Page got grieffed on dlang.org

### ISSUE THREAD

**Issue by Dadoum** [dlang-tour/english#354]
this one on dlang.org: https://tour.dlang.org/tour/en/basics/delegates
this one: https://github.com/dlang-tour/english/blob/master/basics/delegates.md (and does not contains the weird comment)

The added comment is "chiant (signé Sylvain)"; it means "(really) boring/annoying (signed sylvain)" in familiar way.

**Comment by wilzbach** [comment]
Thanks a lot for the report.

Where do you see the comment? I was not able to see.

**Comment by Dadoum** [comment]
![Capture d’écran de 2021-04-02 23-49-40](https://user-images.githubusercontent.com/24679280/113457193-7ac3ba80-940f-11eb-88db-53de22b855ac.png)

**Comment by Dadoum** [comment]
![Capture d’écran de 2021-04-02 23-49-40](https://user-images.githubusercontent.com/24679280/113457292-beb6bf80-940f-11eb-9aff-b00ebdfbc8a0.png)

**Comment by Dadoum** [comment]
I don't know how but it is now fixed now :)
